### ISSUE TITLE
cirno

### ISSUE THREAD

**Issue by foco21** [zlw9991/node-ipc-dependencies-list#1]
cirno

**Comment by Rekunan** [comment]
cirno

**Comment by aequabit** [comment]
I hate Anime but you're doing God's work.

**Comment by MsFloofie** [comment]
cirno

**Comment by zlw9991** [comment]
acknowledged, I will add cirno to the top of the list

**Comment by zlw9991** [comment]
ftr: Actually I like Sakuya Izayoi more, but Cirno is too cute to not use

**Comment by zlw9991** [comment]
cirno added, provide further details if cirno not satisfactory

**Comment by Rekunan** [comment]
![](https://c.tenor.com/6lm-svEn7dEAAAAC/cirno-fumo.gif)

**Comment by theasin** [comment]
the strongest
