### ISSUE TITLE
Describe how to discover node-ipc and other packages written by its author

### ISSUE THREAD

**Issue by prantlf** [zlw9991/node-ipc-dependencies-list#5]
Look for all modules in the local `node_modules` directory, which were known to contain malware:

    npm ls --json peacenotwar | npx jq ".dependencies | keys? | unique | .[]"
    npm ls --json node-ipc | npx jq ".dependencies | keys? | unique | .[]"

Look for all modules in the local `node_modules` directory, which were written by the same author or published in his GitHub repositories:

    npx find-npm-by-author -A "Brandon Nozaki Mille" -R riaevangelist

**Comment by zlw9991** [comment]
Acknowledged, added to the readme, feel free to update here if anything else is needed

**Comment by prantlf** [comment]
Thank you for the quick addition!

**Comment by RocketeerEatingEggs** [comment]
I'll wait until RIA changes his name.
